{{- if .Values.hosts.usePaths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page-ingress
  annotations:
    {{- if not .Values.hosts.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- if .Values.hosts.paths.landing }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    # Rewrite all URLs not ending with a segment containing . or ? with a trailing slash
    # This is necessary to correctly resolve relative paths (e.g. for css files) from the landing page.
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^([^.?]*[^/])$ $1/ redirect;
    {{- if .Values.hosts.paths.tlsSecretName }}
    {{- if .Values.ingress.certManagerAnnotations }}
    cert-manager.io/cluster-issuer: {{ tpl (.Values.ingress.clusterIssuer | toString) . }}
    {{- end }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  {{- if .Values.hosts.tls }}
  tls:
  - hosts:
    - {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
    {{- if .Values.hosts.paths.tlsSecretName }}
    secretName: landing-page-cert-secret
    {{- end }}
  {{- end }}
  rules:
  - host: {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
    http:
      paths:
      - backend:
          service:
            name: landing-page-service
            port:
              number: 80
        path: /{{ if .Values.hosts.paths.landing }}{{ tpl (.Values.hosts.paths.landing | toString) . }}(/|$)(.*){{ end }}
        pathType: Prefix
{{- end }}