apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-api-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-api-access
subjects:
- kind: ServiceAccount
  name: service-api-service-account
  namespace: {{ .Release.Namespace }}