{{- if .Values.hosts.usePaths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /service$1
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
  rules:
  - host: {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
    http:
      paths:
      - backend:
          service:
            name: service-service
            port:
              number: {{ tpl (.Values.hosts.servicePort | toString) . }}
        path: /{{ tpl (.Values.hosts.paths.service | toString) . }}/service($|(/.*))
        pathType: ImplementationSpecific
{{- end }}