apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/service-configmap.yaml") . | sha256sum }}
    spec:
      # we need to be able to create and read sessions
      automountServiceAccountToken: true
      serviceAccountName: service-api-service-account
      containers:
      - name: service-container
        image: {{ tpl (.Values.service.image | toString) . }}
        imagePullPolicy: {{ if .Values.service.imagePullPolicy }}{{ tpl (.Values.service.imagePullPolicy | toString) . }}{{ else }}{{ tpl (.Values.imagePullPolicy | toString) . }}{{ end }}
        ports:
        - name: http
          containerPort: {{ tpl (.Values.service.port | toString) . }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: service-config
      {{- if .Values.service.imagePullSecret }}
      imagePullSecrets:
        - name: {{ tpl (.Values.service.imagePullSecret | toString) . }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-service
  labels:
    app: service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: service
  ports:
    - name: http
      protocol: TCP
      port: {{ tpl (.Values.service.port | toString) . }}
      targetPort: {{ tpl (.Values.service.port | toString) . }}