{{- if not (lookup "cert-manager.io/v1" "ClusterIssuer" "" .Values.issuerprod.name) }}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerprod.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ tpl (.Values.issuer.email | toString) . }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01: 
        ingress:
            class: nginx

{{- end }}