{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" .Values.servicerole.name) }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.servicerole.name }}
  namespace: {{ .Release.Namespace }}
rules:
  -
    apiGroups:
      - ""
      - theia-cloud.io
    resources:
      - sessions
      - workspaces
    verbs: ["list", "create", "watch", "get", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.servicerole.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.servicerole.name }}
subjects:
- kind: ServiceAccount
  name: service-api-service-account
  namespace: {{ .Release.Namespace }}

{{- end }}