apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.servicerole.name }}
rules:
  - apiGroups:
      - ""
      - theia.cloud
    resources:
      - appdefinitions
      - appdefinitions/status
      - sessions
      - sessions/status
      - workspaces
      - workspaces/status
    verbs: ["list", "create", "watch", "get", "patch", "delete"]
  - apiGroups:
      - ""
      - metrics.k8s.io
    resources:
      - pods
    verbs: ["list", "get", "watch"]
