{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" .Values.operatorrole.name) }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operatorrole.name }}
rules:
  -
    apiGroups:
      - ""
      - apiextensions.k8s.io
      - theia.cloud
      - networking.k8s.io
      - apps
    resources:
      - customresourcedefinitions
      - appdefinitions
      - workspaces
      - ingresses
      - sessions
      - persistentvolumes
      - persistentvolumeclaims
      - services
      - configmaps
      - deployments
    verbs: ["list", "create", "watch", "get", "patch", "delete"]

{{- end }}