apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operatorrole.name }}
rules:
  -
    apiGroups:
      - ""
      - apiextensions.k8s.io
      - theia.cloud
      - networking.k8s.io
      - apps
      - coordination.k8s.io
    resources:
      - customresourcedefinitions
      - appdefinitions
      - appdefinitions/status
      - workspaces
      - workspaces/status
      - ingresses
      - sessions
      - sessions/status
      - persistentvolumes
      - persistentvolumeclaims
      - services
      - configmaps
      - deployments
      - leases
    verbs: ["list", "create", "watch", "get", "patch", "delete", "update"]
    